first pass at filtering out unpublished data, as well as unwanted par…
usgs/aqts-capture-field-visit-transform pull request #5
Opened 2020-06-09 21:43 UTC by ssoper-usgs

…ameters

Before making a pull request
----------------------------

- [ ] Make sure all tests run
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
If no JIRA ticket is referenced, describe the changes made. Note anything that you want the reviewers to know while
reviewing your pull request

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the JIRA ticket
- [ ] Assign someone to review unless the change is trivial

2020-06-09 21:54 UTC, ssoper-usgs commented on src/test/resources/testResult/happyPath/discrete_ground_water_old.csv
> +"8BDA141822744BA5E0530100007FD075","393215104490001","2019-06-20 16:34:00","2019-06-20 16:40:01","EIN, EN, GJ, GJS",,"clear, hot, no precip, very light wind","true","{\"LevelsPerformed\": false, \"Co
This file will not be staying.  However, it shows that at least the publish filter is working...

2020-06-10 12:51 UTC, dsteinich requested changes

2020-06-10 12:51 UTC, dsteinich commented on src/main/resources/sql/insertDiscreteGroundWaterData.sql
> +         left join field_visit_readings
leave off the lefts. without data in all the tables we should have no output.

2020-06-10 12:51 UTC, dsteinich commented on src/main/resources/sql/insertDiscreteGroundWaterData.sql
> +    ,field_visit_readings.parameter
We should add the parm_cd (from aq_to_nwis_parm) to this table for use in the load lambda.

2020-06-10 12:51 UTC, dsteinich commented on src/test/resources/testData/data_type_mapping.csv
> +parm_cd,stat_cd,data_type
Per conversations on 6/9/202, 61055 appears to be the only valid one. The rest could be removed (should not be in the real table, can remain here if add value to the tests).

2020-06-10 21:38 UTC, ssoper-usgs commented on src/main/resources/sql/insertDiscreteGroundWaterData.sql
> +    ,aq_to_nwis_parm.parm_cd
Added parm_cd with latest commit here, and on line 13.

2020-06-11 13:32 UTC, dsteinich approved these changes

2020-06-11 17:24 UTC, merged